name: Build and Push Docker image to Docker Hub
permissions:
  id-token: write
  contents: read
on:
  push:
    branches:
      - main

env:
  ACR_NAME: shankartest
  ACR_REPO: shankartest.azurecr.io/shankar-bamserver
  REGION: us-west-1
  ACR_USERNAME: shankartest
  ACR_PASSWORD: zieluBp1OUepT8O7dEpJksFZoXld+eA9qQdXKpOqtq+ACRCnqDtC
  CONTAINER_APPNAME: sg-bamserver
  TEST_AZURE_CREDENTIALS: n_C8Q~myQoBSsinuRtAqSIJsWqapCTE1n0T6XbzZ
  RESOURCE_GROUP: test-rg

jobs:
  build_and_deploy:
    name: 'docker image creation'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure Container Registry login
        run: |
          # az acr login --name ${{ env.ACR_NAME }}
          #az acr login --name ${{ env.ACR_NAME }} --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }}
          az acr login --name ${{ env.ACR_NAME }} --username ${{ env.ACR_USERNAME }} --password ${{ env.ACR_PASSWORD }}

      - run: docker context create builders
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: builders
       
      - name: Set HEAD SHA SHORT
        id: head_sha_short
        run: |
          echo "head_sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Check HEAD SHA SHORT
        run: echo ${{ steps.head_sha_short.outputs.head_sha_short }}
        shell: bash
        
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: |
            latest=false
          images: ${{ env.ACR_REPO }}
          tags: |
            type=raw,value=${{ steps.head_sha_short.outputs.head_sha_short }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: ./DockerFileFolder/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

          
      - name: Execute Azure Container Apps Build and Deploy Action
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.ACR_REPO }}:${{ steps.head_sha_short.outputs.head_sha_short }}
          containerAppName: ${{ env.CONTAINER_APPNAME }}
          containerAppEnvironment: ${{ env.TEST_EXISTING_CONTAINER_APP_ENV }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          disableTelemetry: ${{ env.TEST_DISABLE_TELEMETRY }}
